# -*- coding: utf-8 -*-
"""Lesson_3_tasks_Gulnur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viLdsrNH1ITjroumAeNA_FGO8KrMWM3S
"""

import math
def ft_to_m(length):
  return 0.3048*length #m

def ft2_to_m2(area):
  return ft_to_m(area)*ft_to_m(1) #m2

def ft3_to_m3(volume):
  return ft2_to_m2(volume)*ft_to_m(1) #m3

def in_to_m(length):
  return 0.0254*length

def in2_to_m2(area):
  return 0.00064516*area

def in3_to_m3(volume):
  return (1.6387064e-5)*volume

def oz_to_kg(mass):
  return 0.0283495231*mass

def area_rectangle(length, width):
  return length*width

def volume_rect_cuboid(length, width, depth):
  return length*width*depth

def area_circle(radius):
  return math.pi*radius**2

def volume_cylinder(radius, depth):
  return depth*area_circle(radius)

def density(mass, volume):
  return mass/volume

def weight (density, volume, gravity):
  return density*volume*gravity

def pressure (force, area):
  return force/area

def Pa_bottom_rect_pool(length, width, depth, gravity):
  volume_pool=ft3_to_m3(volume_rect_cuboid(length, width, depth)) #m3
  area_bottom_pool=ft2_to_m2(area_rectangle(length, width)) #m2
  weight_pool_water=weight(density_water, volume_pool,gravity)
  pressure_pool= pressure(weight_pool_water, area_bottom_pool)
  return volume_pool, area_bottom_pool, pressure_pool

def Pa_bottom_circ_pool(radius, depth, gravity):
  volume_pool=ft3_to_m3(volume_cylinder(radius, depth))
  area_bottom_pool=ft2_to_m2(area_circle(radius)) #m2
  weight_pool_water=weight(density_water, volume_pool, gravity)
  pressure_pool= pressure(weight_pool_water, area_bottom_pool)
  return volume_pool, area_bottom_pool, pressure_pool





density_water=density(oz_to_kg(0.58), in3_to_m3(1)) #kg_per_m3
g=9.81 #m/s2
g_moon=1.62 #m/s2

#a)  20 ft long, 10 ft wide, and 6 ft deep
length_a=20 #ft
width_a=10 #ft
depth_a=6 #ft
print('For a pool with (length, width, depth [ft]):', length_a, width_a, depth_a, 'pressure is:', round(Pa_bottom_rect_pool(length_a,width_a, depth_a, g)[2],3), 'Pa')

#b)  10 ft long, 10 ft wide, and 8 ft deep
length_b=10 #ft
width_b=10 #ft
depth_b=8 #ft
print('For a pool with (length, width, depth [ft]):', length_b, width_b, depth_b, 'pressure is:', round(Pa_bottom_rect_pool(length_b,width_b, depth_b, g)[2],3), 'Pa')

#c) 5 ft radius, and 2 ft deep
radius_c=5 #ft
depth_c=2 #ft
print('For a pool with (radius, depth [ft]):', radius_c, depth_c, 'pressure is:', round(Pa_bottom_circ_pool(radius_c, depth_c,g)[2],3), 'Pa')

#d)  9 ft radius, and 1.5 ft deep
radius_d=9 #ft
depth_d=1.5 #ft
print('For a pool with (radius, depth [ft]):', radius_d, depth_d, 'pressure is:', round(Pa_bottom_circ_pool(radius_d, depth_d,g)[2],3), 'Pa')

print("\n-----------------------------------------------------\n")
#How about those pools were in the Moon (gravity=1.62 m/s²)
print("If those pools were in the Moon....\n")
print('For a pool with (length, width, depth [ft]):', length_a, width_a, depth_a, 'pressure is:', round(Pa_bottom_rect_pool(length_a,width_a, depth_a, g_moon)[2],3), 'Pa')
print('For a pool with (length, width, depth [ft]):', length_b, width_b, depth_b, 'pressure is:', round(Pa_bottom_rect_pool(length_b,width_b, depth_b, g_moon)[2],3), 'Pa')
print('For a pool with (radius, depth [ft]):', radius_c, depth_c, 'pressure is:', round(Pa_bottom_circ_pool(radius_c, depth_c,g_moon)[2],3), 'Pa')
print('For a pool with (radius, depth [ft]):', radius_d, depth_d, 'pressure is:', round(Pa_bottom_circ_pool(radius_d, depth_d,g_moon)[2],3), 'Pa')


print('\n------------------------------------------------------------\n')
results = {
    "a": Pa_bottom_rect_pool(20, 10, 6, g),
    "b": Pa_bottom_rect_pool(10, 10, 8, g),
    "c": Pa_bottom_circ_pool(5, 2, g),
    "d": Pa_bottom_circ_pool(9, 1.5, g)
}

# Find maximums
max_volume_case = max(results.items(), key=lambda x: x[1][0])
max_area_case   = max(results.items(), key=lambda x: x[1][1])
max_pressure_case = max(results.items(), key=lambda x: x[1][2])

print("Max volume:", max_volume_case)
print("Max area:", max_area_case)
print("Max pressure:", max_pressure_case)

U = {i for i in range(2, 100)}          # set of numbers 2..99
A = {i for i in range(2, 100) if i%2==0} # set of even numbers
B = {i for i in range(2, 100) if i%3==0} # smultiples of 3
C = {i for i in range(2, 100) if i%5==0 or i%7==0} # multiples of 5 or 7

#a) The set of multiples of 2 and 3
print("The set of multiples of 2 and 3", sorted(A & B))

#b) The set of multiples of 2 or 5 or 7
print("The set of multiples of 2 or 5 or 7", sorted(A | C))

#c) The set of multiples of 3 that aren’t multiples of 5 or 7
print('The set of multiples of 3 that aren’t multiples of 5 or 7', sorted(B-C))

#d) The set of either multiple of 2 or multiple of 3, not multiple of both
print('The set of either multiple of 2 or multiple of 3, not multiple of both', sorted((A|B)-(A&B)))

#e)  The complement of multiples of 2 or 3 or 5 or 7
print('The complement of multiples of 2 or 3 or 5 or 7', sorted(U-(A|B|C)))

# 2. Spell out numbers
num_words = {1: "one", 2: "two", 3: "three"}
numbers = [1, 2, 3]
spelled_out = [num_words[n] for n in numbers]
print("Spell out numbers 1,2,3:", spelled_out)
print('---------------------------------------\n')
# 3. Simple translation of word
translation_dict = {"my": "mon", "red": "rouge", "pen": "stylo"}
phrase = ["my", "red", "pen"]
translated = " ".join(translation_dict[word] for word in phrase)
print('Original', phrase[0], phrase[1], phrase[2])
print("Translation:", translated)
print('---------------------------------------\n')
# 4. Game of Capitals
capitals = {"Portugal": "Lisbon", "France": "Paris", "Germany": "Berlin"}
country = "Portugal"
print(f"What is the capital of {country}?")
print("Answer:", capitals[country])